# Smaple pipeline to build Java web application, run FOD static and dynamic analysis

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package verify'
    options: '-P fortify'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: FortifyOnDemandStatic@7
  inputs:
    FortifyProjects: 'fod'
    ReleaseId: 6547
    FodConnection: 'FOD_BSI_KAL'
    EntitlementPreference: '1'
    InProgressScanActionType: '2'
    RemediationScanPreference: '2'
    PolicyFailAction: '0'