server:
  port: 9080
  error:
    whitelabel:
      enabled: false

messages:
  home: Hello, Guest!

spring:
  profiles: dev
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # template-resolver-order:
    # view-names:
  datasource:
    # h2 database
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ssa_dev
    username: sa
    password: password
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hiberate:
        # h2 database dialect
        dialect: org.hibernate.dialect.H2Dialect
  mvc:
    favicon:
      enabled: false

logging:
  level:
    root: WARN
    com.microfocus: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

