# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Continuous Inspection

on:
  push:
    branches:
      - master
  #    - feature/**
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -Dmaven.compiler.debuglevel=lines,vars,source -Dtest=!UserServiceTest -P fortify,jar -B clean package --file pom.xml

    - name: Zip up source code
      uses: papeloto/action-zip@v1
      with:
        files: src/main/java pom.xml
        dest: fod.zip

    - name: Static Analysis with FOD
      uses: fortify-community-plugins/fod-github-action@v1-alpha
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        fod_credential_type: 'api'
        fod_access_key: ${{ secrets.FOD_ACCESS_KEY }}
        fod_secret_key: ${{ secrets.FOD_SECRET_KEY }}
        bsi_token: ${{ secrets.BSI_TOKEN }}
        fod_release_id: 'master'
        entitlement_preference: 'SubscriptionOnly'
        remediation_scan_preference: 'NonRemediationScanOnly'
        in_progress_scan_action: 'DoNotStartScan'
        audit_preference_id: 'Automated'
        zip_location: 'fod.zip'
        polling_interval: '2'
        notes: 'GitHub Action initiated scan'
        update_commit: true
        update_pr: false
        use_test_data: false
