# This workflow will build a Java project with Maven, upload source code to Fortify on Demand (for static analysis)
# and if successful deploy the application to Heroku

name: Dynamic Security Testing

on:
  workflow_dispatch:
    inputs:
      app-url:
        description: 'Web Application URL'
        required: true
        default: 'https://insecurewebapp.herokuapp.com/'
      wi-policy-id:
        description: 'WebInspect Security Policy Id'
        default: 1008
        required: true

jobs:
  
  webinspect:
    #if: github.ref == 'master' 
    runs-on: Fortify

    # Run dynamic application security testing with WebInspect on-premise and upload results to FOD

    steps:
    - name: DAST with WebInspect
      shell: cmd
      run: |
        wi -s ".\etc\WebScanSettings.xml" -macro ".\etc\Login.webmacro" -u ${{ github.event.inputs.app-url }} -ep ".\wi-iwa.fpr" -ps ${{ github.event.inputs.wi-policy-id }}
      env:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
