# This workflow will execute a DAST scan of the Application URL specified

name: Dynamic Security Testing

on:
  workflow_dispatch:
    inputs:
      ci-cd-id:
        description: 'CICD Identifier'
        default: '548ab08e-93d9-44ce-8e5d-39d582f61b56'
        required: true

jobs:
  
  scancentral-dast:
    #if: github.ref == 'master' 
    #runs-on: Fortify
    runs-on: ubuntu-latest

    # Run dynamic application security testing with WebInspect on-premise and upload results to FOD

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: ScanCentral DAST
      shell: powershell
      run: |
        .\bin\fortify-scancentral-dast.ps1 -ApiUri "$edast-apiuri" -Username "$edast-user" -Password "$edast-password" -CiCdToken ${{ github.event.inputs.ci-cd-id }}
      env:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        edast-apiuri: "${{ secrets.EDAST_APIURI }}"
        edast-user: "${{ secrets.EDAST_USERNAME }}"
        edast-password: "${{ secrets.EDAST_PASSWORD }}"

#    - name: Upload Scan Results
#      uses: actions/upload-artifact@v2.2.0
#      with:
#        path: .\iwa.fpr
 
