# This workflow will execute a DAST scan of the Application URL specified

name: Dynamic Security Testing

on:
  workflow_dispatch:
    inputs:
      app-url:
        description: 'Web Application URL'
        required: true
        default: 'https://insecurewebapp.herokuapp.com/'
      wi-policy-id:
        description: 'WebInspect Security Policy Id'
        default: 1008
        required: true

jobs:
  
  webinspect:
    #if: github.ref == 'master' 
    runs-on: Fortify

    # Run dynamic application security testing with WebInspect on-premise and upload results to FOD

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: DAST with WebInspect
      shell: powershell
      run: |
        $env:Path += ";C:\Micro Focus\Fortify WebInspect"
        wi -s ".\etc\WebScanSettings.xml" -macro ".\etc\Login.webmacro" -u ${{ github.event.inputs.app-url }} -ep ".\iwa.fpr" -ps ${{ github.event.inputs.wi-policy-id }}
      env:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Upload Scan Results
      uses: actions/upload-artifact@v2.2.0
      with:
        path: .\iwa.fpr
 
