# This workflow is for testing GitHub Actions on a previously created/scanned release

name: Fortify GitHub Actions Test

on:
  workflow_dispatch:
    inputs:
      release-id:
        description: 'Fortify Release Id'
        required: true
        default: 56327

jobs:
  
  Fortify-GHA-Test:
    #if: github.ref == 'master' 
    runs-on: ubuntu-latest
    
    steps:

      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v2
        with:
          # Fetch at least the immediate parents so that if this is a pull request then we can checkout the head.
          fetch-depth: 2
      # If this run was triggered by a pull request event, then checkout the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      # Java 8 required by ScanCentral Client and FoD Uploader(Univeral CI Tool)
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Once scan completes, pull SAST issues from Fortify on Demand and generate SARIF output.
      # TODO: Review Action inputs. For most users, these will be the same as used in the Perform SAST Scan step.
      - name: Download Results
        uses: akevinlee/gha-fod-generate-sarif@master
        with:
          base-url: https://emea.fortify.com
          tenant: ${{ secrets.FOD_TENANT }}
          user: ${{ secrets.FOD_USER }}
          password: ${{ secrets.FOD_PAT }}
          release-id: ${{ github.event.inputs.release-id }}
          output: ./sarif/output.sarif        
 
