# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -Dmaven.compiler.debuglevel=lines,vars,source  -P fortify,jar -B clean package --file pom.xml

  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
    - name: Check code is secure
      id: fod
      uses: fod-community-plugins/fod-github-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        fod_access_key: ${{ secrets.FOD_ACCESS_KEY }}
        fod_secret_key: ${{ secrets.FOD_SECRET_KEY }}
        bsi_token: 'ENTER_YOUR_BSI_TOKEN'
        entitlement_preference: 'SubscriptionOnly'
        remediation_scan_preference: 'NonRemediationScanOnly'
        in_progress_scan_action: 'DoNotStartScan'
        zip_location: 'fod.zip'
        polling_interval: '5'
